Npcm.vars["localTbl"] = {}

if (GetLocale() == "ruRU") then
    Npcm.vars["localTbl"]["Players changed."] = "Группа изменена."
    Npcm.vars["localTbl"]["You are now DM."] = "Теперь вы Лидер."
    Npcm.vars["localTbl"]["You are now Assistant."] = "Теперь вы помощник."
    Npcm.vars["localTbl"]["Open / close NPCsMarkers"] = "Открыть / Закрыть NPCsMarkers"
    Npcm.vars["localTbl"]["Force data update"] = "Обновить данные"
    Npcm.vars["localTbl"]["NOT loaded: not compatible with this version of WoW."] = "Не загружен: не совместим с этой версией WoW."
    Npcm.vars["localTbl"]["loaded. Use the minimap button, or enter /npcsmarkers to display its interface."] = "загружен. Используйте кнопку у миникарты или введите /npcsmarkers для отображения интерфейса."
    
    Npcm.vars["localTbl"]["NOT loaded due to addon communication prefix error."] = "Не загружен: ошибка с префиксом коммуникации аддонов."
    
    Npcm.vars["localTbl"]["Ready."] = "Готов."
    Npcm.vars["localTbl"]["settings reset to default."] = "настройки сброшены по умолчанию."
    Npcm.vars["localTbl"]["Unable to communicate."] = "Невозможно установить связь."
    Npcm.vars["localTbl"]["Scale"] = "Масштаб"
    Npcm.vars["localTbl"]["Alpha"] = "Прозрачность"
    Npcm.vars["localTbl"]["must be between 0.5 and 1."] = "должно быть между 0.5 и 1."
    Npcm.vars["localTbl"]["Unable to update Raid Leader markers due to a communication prefix error."] = "Невозможно обновить маркеры лидера рейда: ошибка коммуникации."
    Npcm.vars["localTbl"]["Unable to update client markers due to a communication prefix error."] = "Невозможно обновить маркеры игрока: ошибка коммуникации."
    Npcm.vars["localTbl"]["is not available in LFG/LFR instances or delves."] = "недоступно в подземельях LFG/LFR или в вылазках."
    Npcm.vars["localTbl"]["Warning: you are in instance group!"] = "Внимание: вы в группе подземелья!"
    Npcm.vars["localTbl"]["Warning: not in party or raid!"] = "Внимание: вы не в группе или рейде!"
    Npcm.vars["localTbl"]["Not in home party or raid."] = "Группа отсутствует или недействительна."
    Npcm.vars["localTbl"]["No response from the DM."] = "Нет ответа от Лидера."
    
    Npcm.vars["localTbl"]["Unexpected markers error."] = "Неожиданная ошибка маркеров."
    Npcm.vars["localTbl"]["Data could not be synchronized in combat."] = "Данные не могут быть синхронизированы в бою."
    
    Npcm.vars["localTbl"]["Available commands:"] = "Доступные команды:"
    Npcm.vars["localTbl"]["open addon"] = "открыть аддон"
    Npcm.vars["localTbl"]["close addon"] = "закрыть аддон"
    Npcm.vars["localTbl"]["expand/collapse addon UI"] = "развернуть/свернуть интерфейс аддона"
    Npcm.vars["localTbl"]["display actual settings"] = "показать текущие настройки"
    Npcm.vars["localTbl"]["reset addon UI position and scale"] = "сбросить позицию и масштаб интерфейса аддона"
    Npcm.vars["localTbl"]["perform version and communication check"] = "выполнить проверку версии и коммуникации"
    Npcm.vars["localTbl"]["refresh markers data"] = "обновить данные маркеров"
    Npcm.vars["localTbl"]["About the DM interface:"] = "Об интерфейсе Лидера:"
    Npcm.vars["localTbl"]["Possibility to prepare the markers' characteristics before placing them."] = "Возможность подготовить характеристики маркеров перед их размещением и сделать их видимыми для игроков."
    Npcm.vars["localTbl"]["Markers placed (visible by the players) are colored according to the linked NPC attitude."] = "Размещенные маркеры (видимые игрокам) окрашены в соответствии с отношением связанного NPC."
    Npcm.vars["localTbl"]["Changes in the characteristics of the placed markers are updated in real time on the players' interface."] = "Изменения в характеристиках размещенных маркеров обновляются в реальном времени на интерфейсе игроков."
    Npcm.vars["localTbl"]["To force the display of placed markers characteristics, if a disconnection or synchronization error is encountered, use the 'Update' button."] = "Для принудительного отображения характеристик размещенных маркеров, в случае проблем с подключением, используйте кнопку 'Обновить'."
    Npcm.vars["localTbl"]["from NPCsMarkers: this player doesn't want to be assistant. You should demote this player."] = "от NPCsMarkers: этот игрок не хочет быть помощником. Вам следует понизить этого игрока."

    Npcm.vars["localTbl"]["All players' markers"] = "Маркеры всех игроков"
    Npcm.vars["localTbl"]["Players' marker #"] = "Маркер #"
    Npcm.vars["localTbl"]["updated"] = "обновлено"
    Npcm.vars["localTbl"]["Data updated"] = "Данные обновлены"
    Npcm.vars["localTbl"]["Update request sent to DM."] = "Запрос на обновление отправлен Лидеру."
    Npcm.vars["localTbl"]["Unable to send data to players."] = "Ошибка отправки данных."
    Npcm.vars["localTbl"]["Your version is outdated"] = "Ваша версия устарела"
    Npcm.vars["localTbl"]["New version available:"] = "Доступна новая версия:"
    Npcm.vars["localTbl"]["Markers data saved."] = "Данные маркеров сохранены."
    Npcm.vars["localTbl"]["Markers data loaded."] = "Данные маркеров загружены."
    Npcm.vars["localTbl"]["No saved markers found."] = "Сохраненные данные маркеров не найдены."
    
    Npcm.vars["localTbl"]["Shift-drag to move the frame."] = "Shift + перетаскивание для перемещения панели."
    Npcm.vars["localTbl"]["Double-click to collapse/expand."] = "Двойной клик для сворачивания/разворачивания панели."
    Npcm.vars["localTbl"]["Control-mouse wheel to scale the frame."] = "Ctrl + колесо мыши для изменения масштаба панели."
    Npcm.vars["localTbl"]["Double-click with shift or ctrl to reset the scale."] = "Двойной клик с Shift или Ctrl для сброса масштаба панели."
    Npcm.vars["localTbl"]["Click to place marker."] = "Клик для размещения маркера."
    Npcm.vars["localTbl"]["Shift-click to insert marker icon into active chat box."] = "Shift + клик для вставки значка маркера в активное окно чата."
    Npcm.vars["localTbl"]["Right-click to remove marker or clean marker data."] = "Правый клик для удаления маркера или очистки его данных."
    
    Npcm.vars["localTbl"]["Collapse / Expand"] = "Свернуть / Развернуть"
    Npcm.vars["localTbl"]["Check communications"] = "Проверить связь"
    Npcm.vars["localTbl"]["Ready Check"] = "Проверка готовности"
    Npcm.vars["localTbl"]["Save all NPCs data"] = "Сохранить данные всех NPC"
    Npcm.vars["localTbl"]["Save a copy of NPCs data?\rCopied data can be loaded and used in future RP sessions."] = "Сохранить копию данных NPC?\rСохраненные данные могут быть загружены и использованы в будущих RP-сессиях."
    Npcm.vars["localTbl"]["Restore all saved NPCs data"] = "Восстановить все сохраненные данные NPC"
    Npcm.vars["localTbl"]["Clean all NPCs data"] = "Очистить все данные NPC"
    Npcm.vars["localTbl"]["Settings..."] = "Настройки..."
    Npcm.vars["localTbl"]["Reset Settings"] = "Сбросить настройки"
    Npcm.vars["localTbl"]["Close Addon"] = "Закрыть аддон"
    Npcm.vars["localTbl"]["Yes"] = "Да"
    Npcm.vars["localTbl"]["No"] = "Нет"
    Npcm.vars["localTbl"]["Cancel"] = "Отмена"
    
    Npcm.vars["localTbl"]["This command is reserved for the Dungeon Master."] = "Эта команда зарезервирована для Лидера."
    
    Npcm.vars["localTbl"]["Some markers are still visible to players."] = "Некоторые маркеры все еще видны игрокам."
    Npcm.vars["localTbl"]["No opened chat box."] = "Нет открытого окна чата."
    Npcm.vars["localTbl"]["No opened chat box to insert"] = "Нет открытого окна чата для вставки"
    Npcm.vars["localTbl"]["Unable to whisp to the Dungeon Master: empty name."] = "Невозможно шепнуть Лидеру: имя пусто."
    
    Npcm.vars["localTbl"]["You are now an"] = "Теперь вы"
    Npcm.vars["localTbl"]["If you don't want to be, ask the Dungeon Master to demote you."] = "Если вы не хотите быть помощником, попросите Лидера понизить вас."
    Npcm.vars["localTbl"]["Ask the DM"] = "Спросить"
    Npcm.vars["localTbl"]["Don't ask"] = "Не спрашивать"
    Npcm.vars["localTbl"]["Click to update markers."] = "Клик для обновления маркеров."
    
    Npcm.vars["localTbl"]["unable to find player."] = "Игрок не найден."
    Npcm.vars["localTbl"]["Update"] = "Обновить"
    Npcm.vars["localTbl"]["List Update"] = "Обновить список"
    Npcm.vars["localTbl"]["Close"] = "Закрыть"
    Npcm.vars["localTbl"]["Name"] = "Имя"
    Npcm.vars["localTbl"]["HP"] = "Здоровье"
    Npcm.vars["localTbl"]["Checking players..."] = "Поиск игроков..."
    
    Npcm.vars["localTbl"]["players list"] = "список игроков"
    Npcm.vars["localTbl"]["Informations"] = "Информация"
    
    Npcm.vars["localTbl"]["Open/close"] = "Открыть/Закрыть"
    Npcm.vars["localTbl"]["Right-click to display config."] = "Правый клик для отображения настроек."
    
    Npcm.vars["localTbl"]["DM interface"] = "Интерфейс Лидера"
    Npcm.vars["localTbl"]["Scale:"] = "Масштаб:"
    Npcm.vars["localTbl"]["Transparency:"] = "Прозрачность:"
    Npcm.vars["localTbl"]["Dark interface"] = "Темный интерфейс"
    Npcm.vars["localTbl"]["NPCs HP Bar Accuracy:"] = "Точность полос здоровья NPC:"
    Npcm.vars["localTbl"]["Misc"] = "Разное"
    Npcm.vars["localTbl"]["Forced refresh on Raid Leader login"] = "Принудительное обновление при входе лидера рейда"
    Npcm.vars["localTbl"]["Sounds"] = "Звуки"
    Npcm.vars["localTbl"]["DM sounds"] = "Звуки Лидера"
    Npcm.vars["localTbl"]["Players sounds"] = "Звуки игроков"
    Npcm.vars["localTbl"]["Supported slash-commands"] = "Поддерживаемые команды"
    Npcm.vars["localTbl"]["is already running."] = "уже запущен."
    Npcm.vars["localTbl"]["Show DM interface"] = "Показать интерфейс Лидера"
    --Npcm.vars["localTbl"]["change will take effect after reloading UI."] = "изменения вступят в силу после перезагрузки интерфейса."
end